### ISSUE TITLE
Go2+D1 Model Not Moving After RL Importing

### ISSUE THREAD

**Issue by vigorlee** [Zhefan-Xu/isaac-go2-ros2#4]
Hi there,

First of all, thank you for your excellent work and support. 
I want to ask on the issue why the go2+d1 model falls over when placed in, but it can move normally when training in Isaac Lab. We have already set the robotic arm's mass to 0.
![6f933bdcc884c34b59edbe1dcf084e8](https://github.com/user-attachments/assets/f51a3465-c89b-4a23-9b19-14a09aaf8d97)
![2c75e07547366a319ed1a8689e3bd3a](https://github.com/user-attachments/assets/7fd8d2cd-961a-4ef9-8e15-dec8c86c927f)
Thank you so much for your time and assistance.

**Comment by Wesley-Le** [comment]
"D1 has not been trained separately; it has only been integrated with go2 and imported into Isaac Lab. The combined training process mimics the original training approach of go2 in Isaac Lab.

**Comment by vigorlee** [comment]
we use the PPO implementation from rsl-rl to train whole body this policy in Isaaclab Env.
We have verified that there are no issues with model play in the isaaclab.
However, when deployed in the isaac-go2-ros2 environment, the robotic arm seems to crush moving objects, which might be an issue with the arm's training policy.

**Comment by Zhefan-Xu** [comment]
Could you verify that the observation and parameters are the same as the isaaclab environment?
